export const GET_ALL_POKEMONS="GET_ALL_POKEMONS"
export const LOAD_POKEMON="LOAD_POKEMON"

export const GET_ALL_TYPES= "GET_ALL_TYPES"

export const SET_FILTER_BY_ORIGIN = 'SET_FILTER_BY_ORIGIN'
export const SET_FILTER_BY_TYPE = 'SET_FILTER_BY_TYPE'
export const ORDER = 'ORDER'